name: Build and Deploy to Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Commit ID and Date
        run: |
          COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
          COMMIT_DATE=$(TZ='Asia/Tokyo' date +'%Y/%m/%d %H:%M:%S')
          sed -i "s/COMMIT_HASH_PLACEHOLDER/$COMMIT_HASH/g" index.html
          sed -i "s/COMMIT_DATE_PLACEHOLDER/$COMMIT_DATE/g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
